version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gbhfns
      POSTGRES_DB: filesystem
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  minio:
    image: quay.io/minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_DOMAIN: localhost
    command: server --console-address ":9001" /data
    volumes:
      - minio_storage:/data

  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
        
  user-app:
    build:
      context: ./user-app
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/filesystem
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: gbhfns
        SPRING_REDIS_HOST: redis
        SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis

  forum-core:
    build:
      context: ./forum-core
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/filesystem
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: gbhfns
    depends_on:
      - postgres
    
  file-app:
    build:
      context: ./file-app
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/filesystem
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: gbhfns
    depends_on:
      - postgres
      - minio
      
volumes:
  minio_storage: {}
