spring:
  application:
    name: GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: file-service
          uri: lb://FILE-SERVICE
          predicates:
            - Path=/api/file/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/account/**

        - id: forum-service
          uri: lb://FORUM-SERVICE
          predicates:
            - Path=/api/forum/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notification/**

jwt:
  secret: AbdaasdasdasdasfasgasASFASF

