spring:
  application:
    name: GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: file-service
          uri: http://file-app:8083
          predicates:
            - Path=/api/file/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: http://user-app:8081
          predicates:
            - Path=/api/account/**
          filters:
            - AuthenticationFilter

        - id: forum-service
          uri: http://forum-core:8082
          predicates:
            - Path=/api/forum/**
          filters:
            - AuthenticationFilter

        - id: notification-service
          uri: http://notification-app:8084
          predicates:
            - Path=/api/notification/**

jwt:
  secret: AbdaasdasdasdasfasgasASFASF

