spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userapp
    username: postgres
    password: gbhfns
    driverClassName: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: http://localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka