server:
<<<<<<< HEAD
  port: 8010
=======
  port: 8081
>>>>>>> 652e6b5cc00632fb43cd0fa859c1d48e64471d8d

jwt:
  secret: AbdaasdasdasdasfasgasASFASF
  expiration: 1h

refresh:
  expiration: 1d

spring:
<<<<<<< HEAD
  datasource:
    url: jdbc:postgresql://localhost:5432/FileSystem
=======
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/filesystem
>>>>>>> 652e6b5cc00632fb43cd0fa859c1d48e64471d8d
    username: postgres
    password: gbhfns
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
<<<<<<< HEAD
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
=======
      ddl-auto: create
    show-sql: true
  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
>>>>>>> 652e6b5cc00632fb43cd0fa859c1d48e64471d8d
