server:
  port: 8082

jwt:
  secret: AbdaasdasdasdasfasgasASFASF
  expiration: 1h

refresh:
  expiration: 1d

spring:
  application:
    name: FORUM-SERVICE
  datasource:
    url: jdbc:postgresql://postgres_for:5432/forumapp
    username: postgres
    password: gbhfns
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
        defaultZone: http://service-registry:8761/eureka
