spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/forumapp
    username: postgres
    password: gbhfns
    driverClassName: org.postgresql.Driver

  kafka:
    bootstrap-servers: http://localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka
