server:
  port: 8082

jwt:
  secret: AbdaasdasdasdasfasgasASFASF
  expiration: 1h

spring:
  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml
  application:
    name: FORUM-SERVICE
  datasource:
    url: jdbc:postgresql://postgres_for:5434/forumapp
    username: postgres
    password: gbhfns
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

eureka:
  client:
    service-url:
        defaultZone: http://service-registry:8761/eureka
