package com.hits.common.Core.Notification.Proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NotificationDTO.proto
// Protobuf Java Version: 4.26.1

public final class NotificationDTOOuterClass {
  private NotificationDTOOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      NotificationDTOOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code NotificationChannel}
   */
  public enum NotificationChannel
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EMAIL = 0;</code>
     */
    EMAIL(0),
    /**
     * <code>MESSENGER = 1;</code>
     */
    MESSENGER(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        NotificationChannel.class.getName());
    }
    /**
     * <code>EMAIL = 0;</code>
     */
    public static final int EMAIL_VALUE = 0;
    /**
     * <code>MESSENGER = 1;</code>
     */
    public static final int MESSENGER_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static NotificationChannel valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static NotificationChannel forNumber(int value) {
      switch (value) {
        case 0: return EMAIL;
        case 1: return MESSENGER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<NotificationChannel>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        NotificationChannel> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<NotificationChannel>() {
            public NotificationChannel findValueByNumber(int number) {
              return NotificationChannel.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return NotificationDTOOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final NotificationChannel[] VALUES = values();

    public static NotificationChannel valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private NotificationChannel(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:NotificationChannel)
  }

  public interface NotificationDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NotificationDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    String getTitle();
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string content = 2;</code>
     * @return The content.
     */
    String getContent();
    /**
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>string user_id = 3;</code>
     * @return The userId.
     */
    String getUserId();
    /**
     * <code>string user_id = 3;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    String getEmail();
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string login = 5;</code>
     * @return The login.
     */
    String getLogin();
    /**
     * <code>string login = 5;</code>
     * @return The bytes for login.
     */
    com.google.protobuf.ByteString
        getLoginBytes();

    /**
     * <code>.google.protobuf.Timestamp create_time = 6;</code>
     * @return Whether the createTime field is set.
     */
    boolean hasCreateTime();
    /**
     * <code>.google.protobuf.Timestamp create_time = 6;</code>
     * @return The createTime.
     */
    com.google.protobuf.Timestamp getCreateTime();
    /**
     * <code>.google.protobuf.Timestamp create_time = 6;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();

    /**
     * <code>repeated .NotificationChannel channel_list = 7;</code>
     * @return A list containing the channelList.
     */
    java.util.List<NotificationChannel> getChannelListList();
    /**
     * <code>repeated .NotificationChannel channel_list = 7;</code>
     * @return The count of channelList.
     */
    int getChannelListCount();
    /**
     * <code>repeated .NotificationChannel channel_list = 7;</code>
     * @param index The index of the element to return.
     * @return The channelList at the given index.
     */
    NotificationChannel getChannelList(int index);
    /**
     * <code>repeated .NotificationChannel channel_list = 7;</code>
     * @return A list containing the enum numeric values on the wire for channelList.
     */
    java.util.List<Integer>
    getChannelListValueList();
    /**
     * <code>repeated .NotificationChannel channel_list = 7;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of channelList at the given index.
     */
    int getChannelListValue(int index);

    /**
     * <code>bool need_in_history = 8;</code>
     * @return The needInHistory.
     */
    boolean getNeedInHistory();
  }
  /**
   * Protobuf type {@code NotificationDTO}
   */
  public static final class NotificationDTO extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NotificationDTO)
      NotificationDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        NotificationDTO.class.getName());
    }
    // Use NotificationDTO.newBuilder() to construct.
    private NotificationDTO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private NotificationDTO() {
      title_ = "";
      content_ = "";
      userId_ = "";
      email_ = "";
      login_ = "";
      channelList_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NotificationDTOOuterClass.internal_static_NotificationDTO_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NotificationDTOOuterClass.internal_static_NotificationDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NotificationDTO.class, Builder.class);
    }

    private int bitField0_;
    public static final int TITLE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object title_ = "";
    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    @Override
    public String getTitle() {
      Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    @Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object content_ = "";
    /**
     * <code>string content = 2;</code>
     * @return The content.
     */
    @Override
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    @Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_ID_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object userId_ = "";
    /**
     * <code>string user_id = 3;</code>
     * @return The userId.
     */
    @Override
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string user_id = 3;</code>
     * @return The bytes for userId.
     */
    @Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile Object email_ = "";
    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    @Override
    public String getEmail() {
      Object ref = email_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    @Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGIN_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile Object login_ = "";
    /**
     * <code>string login = 5;</code>
     * @return The login.
     */
    @Override
    public String getLogin() {
      Object ref = login_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        login_ = s;
        return s;
      }
    }
    /**
     * <code>string login = 5;</code>
     * @return The bytes for login.
     */
    @Override
    public com.google.protobuf.ByteString
        getLoginBytes() {
      Object ref = login_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        login_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATE_TIME_FIELD_NUMBER = 6;
    private com.google.protobuf.Timestamp createTime_;
    /**
     * <code>.google.protobuf.Timestamp create_time = 6;</code>
     * @return Whether the createTime field is set.
     */
    @Override
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 6;</code>
     * @return The createTime.
     */
    @Override
    public com.google.protobuf.Timestamp getCreateTime() {
      return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 6;</code>
     */
    @Override
    public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
      return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
    }

    public static final int CHANNEL_LIST_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private java.util.List<Integer> channelList_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        Integer, NotificationChannel> channelList_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                Integer, NotificationChannel>() {
              public NotificationChannel convert(Integer from) {
                NotificationChannel result = NotificationChannel.forNumber(from);
                return result == null ? NotificationChannel.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .NotificationChannel channel_list = 7;</code>
     * @return A list containing the channelList.
     */
    @Override
    public java.util.List<NotificationChannel> getChannelListList() {
      return new com.google.protobuf.Internal.ListAdapter<
          Integer, NotificationChannel>(channelList_, channelList_converter_);
    }
    /**
     * <code>repeated .NotificationChannel channel_list = 7;</code>
     * @return The count of channelList.
     */
    @Override
    public int getChannelListCount() {
      return channelList_.size();
    }
    /**
     * <code>repeated .NotificationChannel channel_list = 7;</code>
     * @param index The index of the element to return.
     * @return The channelList at the given index.
     */
    @Override
    public NotificationChannel getChannelList(int index) {
      return channelList_converter_.convert(channelList_.get(index));
    }
    /**
     * <code>repeated .NotificationChannel channel_list = 7;</code>
     * @return A list containing the enum numeric values on the wire for channelList.
     */
    @Override
    public java.util.List<Integer>
    getChannelListValueList() {
      return channelList_;
    }
    /**
     * <code>repeated .NotificationChannel channel_list = 7;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of channelList at the given index.
     */
    @Override
    public int getChannelListValue(int index) {
      return channelList_.get(index);
    }
    private int channelListMemoizedSerializedSize;

    public static final int NEED_IN_HISTORY_FIELD_NUMBER = 8;
    private boolean needInHistory_ = false;
    /**
     * <code>bool need_in_history = 8;</code>
     * @return The needInHistory.
     */
    @Override
    public boolean getNeedInHistory() {
      return needInHistory_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, title_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, content_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, userId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, email_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(login_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, login_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(6, getCreateTime());
      }
      if (getChannelListList().size() > 0) {
        output.writeUInt32NoTag(58);
        output.writeUInt32NoTag(channelListMemoizedSerializedSize);
      }
      for (int i = 0; i < channelList_.size(); i++) {
        output.writeEnumNoTag(channelList_.get(i));
      }
      if (needInHistory_ != false) {
        output.writeBool(8, needInHistory_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, title_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, content_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, userId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, email_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(login_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, login_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getCreateTime());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < channelList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(channelList_.get(i));
        }
        size += dataSize;
        if (!getChannelListList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(dataSize);
        }channelListMemoizedSerializedSize = dataSize;
      }
      if (needInHistory_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, needInHistory_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NotificationDTO)) {
        return super.equals(obj);
      }
      NotificationDTO other = (NotificationDTO) obj;

      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getLogin()
          .equals(other.getLogin())) return false;
      if (hasCreateTime() != other.hasCreateTime()) return false;
      if (hasCreateTime()) {
        if (!getCreateTime()
            .equals(other.getCreateTime())) return false;
      }
      if (!channelList_.equals(other.channelList_)) return false;
      if (getNeedInHistory()
          != other.getNeedInHistory()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + LOGIN_FIELD_NUMBER;
      hash = (53 * hash) + getLogin().hashCode();
      if (hasCreateTime()) {
        hash = (37 * hash) + CREATE_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getCreateTime().hashCode();
      }
      if (getChannelListCount() > 0) {
        hash = (37 * hash) + CHANNEL_LIST_FIELD_NUMBER;
        hash = (53 * hash) + channelList_.hashCode();
      }
      hash = (37 * hash) + NEED_IN_HISTORY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNeedInHistory());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NotificationDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NotificationDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NotificationDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NotificationDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NotificationDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NotificationDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NotificationDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static NotificationDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static NotificationDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static NotificationDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NotificationDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static NotificationDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NotificationDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NotificationDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NotificationDTO)
        NotificationDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NotificationDTOOuterClass.internal_static_NotificationDTO_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NotificationDTOOuterClass.internal_static_NotificationDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NotificationDTO.class, Builder.class);
      }

      // Construct using NotificationDTOOuterClass.NotificationDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getCreateTimeFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        title_ = "";
        content_ = "";
        userId_ = "";
        email_ = "";
        login_ = "";
        createTime_ = null;
        if (createTimeBuilder_ != null) {
          createTimeBuilder_.dispose();
          createTimeBuilder_ = null;
        }
        channelList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        needInHistory_ = false;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NotificationDTOOuterClass.internal_static_NotificationDTO_descriptor;
      }

      @Override
      public NotificationDTO getDefaultInstanceForType() {
        return NotificationDTO.getDefaultInstance();
      }

      @Override
      public NotificationDTO build() {
        NotificationDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public NotificationDTO buildPartial() {
        NotificationDTO result = new NotificationDTO(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(NotificationDTO result) {
        if (((bitField0_ & 0x00000040) != 0)) {
          channelList_ = java.util.Collections.unmodifiableList(channelList_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.channelList_ = channelList_;
      }

      private void buildPartial0(NotificationDTO result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.title_ = title_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.content_ = content_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.email_ = email_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.login_ = login_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.createTime_ = createTimeBuilder_ == null
              ? createTime_
              : createTimeBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.needInHistory_ = needInHistory_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NotificationDTO) {
          return mergeFrom((NotificationDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NotificationDTO other) {
        if (other == NotificationDTO.getDefaultInstance()) return this;
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getLogin().isEmpty()) {
          login_ = other.login_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.hasCreateTime()) {
          mergeCreateTime(other.getCreateTime());
        }
        if (!other.channelList_.isEmpty()) {
          if (channelList_.isEmpty()) {
            channelList_ = other.channelList_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureChannelListIsMutable();
            channelList_.addAll(other.channelList_);
          }
          onChanged();
        }
        if (other.getNeedInHistory() != false) {
          setNeedInHistory(other.getNeedInHistory());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                title_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                content_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                userId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                email_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                login_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getCreateTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 56: {
                int tmpRaw = input.readEnum();
                ensureChannelListIsMutable();
                channelList_.add(tmpRaw);
                break;
              } // case 56
              case 58: {
                int length = input.readRawVarint32();
                int oldLimit = input.pushLimit(length);
                while(input.getBytesUntilLimit() > 0) {
                  int tmpRaw = input.readEnum();
                  ensureChannelListIsMutable();
                  channelList_.add(tmpRaw);
                }
                input.popLimit(oldLimit);
                break;
              } // case 58
              case 64: {
                needInHistory_ = input.readBool();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object title_ = "";
      /**
       * <code>string title = 1;</code>
       * @return The title.
       */
      public String getTitle() {
        Object ref = title_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        title_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        title_ = getDefaultInstance().getTitle();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        title_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>string content = 2;</code>
       * @return The content.
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        content_ = getDefaultInstance().getContent();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        content_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private Object userId_ = "";
      /**
       * <code>string user_id = 3;</code>
       * @return The userId.
       */
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string user_id = 3;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_id = 3;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        userId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        userId_ = getDefaultInstance().getUserId();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 3;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        userId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private Object email_ = "";
      /**
       * <code>string email = 4;</code>
       * @return The email.
       */
      public String getEmail() {
        Object ref = email_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        email_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        email_ = getDefaultInstance().getEmail();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        email_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private Object login_ = "";
      /**
       * <code>string login = 5;</code>
       * @return The login.
       */
      public String getLogin() {
        Object ref = login_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          login_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string login = 5;</code>
       * @return The bytes for login.
       */
      public com.google.protobuf.ByteString
          getLoginBytes() {
        Object ref = login_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          login_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string login = 5;</code>
       * @param value The login to set.
       * @return This builder for chaining.
       */
      public Builder setLogin(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        login_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string login = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogin() {
        login_ = getDefaultInstance().getLogin();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string login = 5;</code>
       * @param value The bytes for login to set.
       * @return This builder for chaining.
       */
      public Builder setLoginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        login_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp createTime_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp create_time = 6;</code>
       * @return Whether the createTime field is set.
       */
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 6;</code>
       * @return The createTime.
       */
      public com.google.protobuf.Timestamp getCreateTime() {
        if (createTimeBuilder_ == null) {
          return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
        } else {
          return createTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 6;</code>
       */
      public Builder setCreateTime(com.google.protobuf.Timestamp value) {
        if (createTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createTime_ = value;
        } else {
          createTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 6;</code>
       */
      public Builder setCreateTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (createTimeBuilder_ == null) {
          createTime_ = builderForValue.build();
        } else {
          createTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 6;</code>
       */
      public Builder mergeCreateTime(com.google.protobuf.Timestamp value) {
        if (createTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0) &&
            createTime_ != null &&
            createTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getCreateTimeBuilder().mergeFrom(value);
          } else {
            createTime_ = value;
          }
        } else {
          createTimeBuilder_.mergeFrom(value);
        }
        if (createTime_ != null) {
          bitField0_ |= 0x00000020;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 6;</code>
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        createTime_ = null;
        if (createTimeBuilder_ != null) {
          createTimeBuilder_.dispose();
          createTimeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 6;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCreateTimeBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getCreateTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 6;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
        if (createTimeBuilder_ != null) {
          return createTimeBuilder_.getMessageOrBuilder();
        } else {
          return createTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCreateTimeFieldBuilder() {
        if (createTimeBuilder_ == null) {
          createTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCreateTime(),
                  getParentForChildren(),
                  isClean());
          createTime_ = null;
        }
        return createTimeBuilder_;
      }

      private java.util.List<Integer> channelList_ =
        java.util.Collections.emptyList();
      private void ensureChannelListIsMutable() {
        if (!((bitField0_ & 0x00000040) != 0)) {
          channelList_ = new java.util.ArrayList<Integer>(channelList_);
          bitField0_ |= 0x00000040;
        }
      }
      /**
       * <code>repeated .NotificationChannel channel_list = 7;</code>
       * @return A list containing the channelList.
       */
      public java.util.List<NotificationChannel> getChannelListList() {
        return new com.google.protobuf.Internal.ListAdapter<
            Integer, NotificationChannel>(channelList_, channelList_converter_);
      }
      /**
       * <code>repeated .NotificationChannel channel_list = 7;</code>
       * @return The count of channelList.
       */
      public int getChannelListCount() {
        return channelList_.size();
      }
      /**
       * <code>repeated .NotificationChannel channel_list = 7;</code>
       * @param index The index of the element to return.
       * @return The channelList at the given index.
       */
      public NotificationChannel getChannelList(int index) {
        return channelList_converter_.convert(channelList_.get(index));
      }
      /**
       * <code>repeated .NotificationChannel channel_list = 7;</code>
       * @param index The index to set the value at.
       * @param value The channelList to set.
       * @return This builder for chaining.
       */
      public Builder setChannelList(
          int index, NotificationChannel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChannelListIsMutable();
        channelList_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .NotificationChannel channel_list = 7;</code>
       * @param value The channelList to add.
       * @return This builder for chaining.
       */
      public Builder addChannelList(NotificationChannel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChannelListIsMutable();
        channelList_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .NotificationChannel channel_list = 7;</code>
       * @param values The channelList to add.
       * @return This builder for chaining.
       */
      public Builder addAllChannelList(
          Iterable<? extends NotificationChannel> values) {
        ensureChannelListIsMutable();
        for (NotificationChannel value : values) {
          channelList_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .NotificationChannel channel_list = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannelList() {
        channelList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .NotificationChannel channel_list = 7;</code>
       * @return A list containing the enum numeric values on the wire for channelList.
       */
      public java.util.List<Integer>
      getChannelListValueList() {
        return java.util.Collections.unmodifiableList(channelList_);
      }
      /**
       * <code>repeated .NotificationChannel channel_list = 7;</code>
       * @param index The index of the value to return.
       * @return The enum numeric value on the wire of channelList at the given index.
       */
      public int getChannelListValue(int index) {
        return channelList_.get(index);
      }
      /**
       * <code>repeated .NotificationChannel channel_list = 7;</code>
       * @param index The index to set the value at.
       * @param value The enum numeric value on the wire for channelList to set.
       * @return This builder for chaining.
       */
      public Builder setChannelListValue(
          int index, int value) {
        ensureChannelListIsMutable();
        channelList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .NotificationChannel channel_list = 7;</code>
       * @param value The enum numeric value on the wire for channelList to add.
       * @return This builder for chaining.
       */
      public Builder addChannelListValue(int value) {
        ensureChannelListIsMutable();
        channelList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .NotificationChannel channel_list = 7;</code>
       * @param values The enum numeric values on the wire for channelList to add.
       * @return This builder for chaining.
       */
      public Builder addAllChannelListValue(
          Iterable<Integer> values) {
        ensureChannelListIsMutable();
        for (int value : values) {
          channelList_.add(value);
        }
        onChanged();
        return this;
      }

      private boolean needInHistory_ ;
      /**
       * <code>bool need_in_history = 8;</code>
       * @return The needInHistory.
       */
      @Override
      public boolean getNeedInHistory() {
        return needInHistory_;
      }
      /**
       * <code>bool need_in_history = 8;</code>
       * @param value The needInHistory to set.
       * @return This builder for chaining.
       */
      public Builder setNeedInHistory(boolean value) {

        needInHistory_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>bool need_in_history = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearNeedInHistory() {
        bitField0_ = (bitField0_ & ~0x00000080);
        needInHistory_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NotificationDTO)
    }

    // @@protoc_insertion_point(class_scope:NotificationDTO)
    private static final NotificationDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NotificationDTO();
    }

    public static NotificationDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NotificationDTO>
        PARSER = new com.google.protobuf.AbstractParser<NotificationDTO>() {
      @Override
      public NotificationDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NotificationDTO> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<NotificationDTO> getParserForType() {
      return PARSER;
    }

    @Override
    public NotificationDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NotificationDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NotificationDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025NotificationDTO.proto\032\037google/protobuf" +
      "/timestamp.proto\"\326\001\n\017NotificationDTO\022\r\n\005" +
      "title\030\001 \001(\t\022\017\n\007content\030\002 \001(\t\022\017\n\007user_id\030" +
      "\003 \001(\t\022\r\n\005email\030\004 \001(\t\022\r\n\005login\030\005 \001(\t\022/\n\013c" +
      "reate_time\030\006 \001(\0132\032.google.protobuf.Times" +
      "tamp\022*\n\014channel_list\030\007 \003(\0162\024.Notificatio" +
      "nChannel\022\027\n\017need_in_history\030\010 \001(\010*/\n\023Not" +
      "ificationChannel\022\t\n\005EMAIL\020\000\022\r\n\tMESSENGER" +
      "\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_NotificationDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NotificationDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NotificationDTO_descriptor,
        new String[] { "Title", "Content", "UserId", "Email", "Login", "CreateTime", "ChannelList", "NeedInHistory", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
