spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notificationapp
    username: postgres
    password: gbhfns
    driverClassName: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka