server:
  port: 8084

jwt:
  secret: AbdaasdasdasdasfasgasASFASF
  expiration: 1h

refresh:
  expiration: 1d

spring:
  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml

  application:
    name: NOTIFICATION-SERVICE

  datasource:
    url: jdbc:postgresql://postgres_notif:5435/notificationapp
    username: postgres
    password: gbhfns
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: gbhfns47@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka

springdoc:
  api-docs:
    path: /api-docs